theme: jekyll-theme-slate
title: 2020 United States Presidentiial Election Analysis
description: This blog is the record of my assignments for the Harvard College course Government 1347: Election Analytics. Blog posts will appear on Saturdays, consistent with the assingment requirments.
